#############################################################################
# Makefile for building: Fireflock.app/Contents/MacOS/Fireflock
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sat Nov 5 14:19:09 2011
# Project:  fireflock.pro
# Template: app
# Command: /Users/feross/QtSDK/Desktop/Qt/474/gcc/bin/qmake -o Makefile fireflock.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/474/gcc/mkspecs/default -I. -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtCore.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtNetwork.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtNetwork -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtGui.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtWebKit.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtWebKit -I../../QtSDK/Desktop/Qt/474/gcc/include -I. -F/Users/feross/QtSDK/Desktop/Qt/474/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/feross/QtSDK/Desktop/Qt/474/gcc/lib -L/Users/feross/QtSDK/Desktop/Qt/474/gcc/lib -framework QtWebKit -framework QtGui -framework QtNetwork -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/feross/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = fireflock.cpp \
		main.cpp \
		mainwindow.cpp moc_fireflock.cpp \
		moc_mainwindow.cpp \
		qrc_fireflock.cpp
OBJECTS       = fireflock.o \
		main.o \
		mainwindow.o \
		moc_fireflock.o \
		moc_mainwindow.o \
		qrc_fireflock.o
DIST          = ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		fireflock.pro
QMAKE_TARGET  = Fireflock
DESTDIR       = 
TARGET        = Fireflock.app/Contents/MacOS/Fireflock

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Fireflock.app/Contents/PkgInfo Fireflock.app/Contents/Resources/empty.lproj Fireflock.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Fireflock.app/Contents/MacOS/ || $(MKDIR) Fireflock.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fireflock.pro  ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/default/qmake.conf ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile fireflock.pro
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile fireflock.pro

Fireflock.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) Fireflock.app/Contents || $(MKDIR) Fireflock.app/Contents 
	@$(DEL_FILE) Fireflock.app/Contents/PkgInfo
	@echo "APPL????" >Fireflock.app/Contents/PkgInfo
Fireflock.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) Fireflock.app/Contents/Resources || $(MKDIR) Fireflock.app/Contents/Resources 
	@touch Fireflock.app/Contents/Resources/empty.lproj
	
Fireflock.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) Fireflock.app/Contents || $(MKDIR) Fireflock.app/Contents 
	@$(DEL_FILE) Fireflock.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Fireflock,g" -e "s,@TYPEINFO@,????,g" ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/default/Info.plist.app >Fireflock.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/Fireflock1.0.0 || $(MKDIR) .tmp/Fireflock1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Fireflock1.0.0/ && $(COPY_FILE) --parents fireflock.h mainwindow.h .tmp/Fireflock1.0.0/ && $(COPY_FILE) --parents resources/fireflock.qrc .tmp/Fireflock1.0.0/ && $(COPY_FILE) --parents fireflock.cpp main.cpp mainwindow.cpp .tmp/Fireflock1.0.0/ && (cd `dirname .tmp/Fireflock1.0.0` && $(TAR) Fireflock1.0.0.tar Fireflock1.0.0 && $(COMPRESS) Fireflock1.0.0.tar) && $(MOVE) `dirname .tmp/Fireflock1.0.0`/Fireflock1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Fireflock1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Fireflock.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_fireflock.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fireflock.cpp moc_mainwindow.cpp
moc_fireflock.cpp: fireflock.h
	/Users/feross/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ fireflock.h -o moc_fireflock.cpp

moc_mainwindow.cpp: mainwindow.h
	/Users/feross/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_fireflock.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_fireflock.cpp
qrc_fireflock.cpp: resources/fireflock.qrc \
		resources/index.html
	/Users/feross/QtSDK/Desktop/Qt/474/gcc/bin/rcc -name fireflock resources/fireflock.qrc -o qrc_fireflock.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

fireflock.o: fireflock.cpp fireflock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fireflock.o fireflock.cpp

main.o: main.cpp fireflock.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		fireflock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_fireflock.o: moc_fireflock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fireflock.o moc_fireflock.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_fireflock.o: qrc_fireflock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_fireflock.o qrc_fireflock.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

